version: '3.5'
services:
    marmantenimiento:
        image: 'mariadbtpi'
        build: ./MariaDB/.
        container_name: 'mariamicro'
        environment: 
            - 'MYSQL_ROOT_PASSWORD=1234'
        ports:
            - '3300:3306'
        volumes:
            - ./mariadblMantenimientoVol:/var/lib/mysql
        networks: 
            mantenimiento_net:
                ipv4_address: 172.25.0.28
    paymantenimiento: 
        image: 'payaramicro'
        build: ./Payaramicro/.   
        container_name: 'paymicro'
        command: dockerize -wait http://172.25.0.28:3300/mantenimienoPC -timeout 15s
        depends_on:
            - marmantenimiento
        ports:
            - "8080:8181"
        networks: 
            mantenimiento_net:
                ipv4_address: 172.25.0.29
    nodemantenimiento:
        image: 'nodetpi'
        build: ./Frontend/.
        container_name: 'nodetpi'
        command: dockerize -wait http://172.25.0.29:8181/MantenimientoTPI-web
        depends_on:
            - paymantenimiento
        ports:
            - '3000:3000'
        networks: 
            mantenimiento_net:
                ipv4_address: 172.25.0.30
networks: 
    mantenimiento_net:
        ipam:
            driver: default
            config:
            - subnet: 172.25.0.0/16
